databases:
  - name: expressify_production
    databaseName: expressify_production
    user: rails

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expressify_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false