default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: expressify_development

test:
  <<: *default
  database: expressify_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: expressify_production
  username: expressify
  password: <%= ENV["EXPRESSIFY_DATABASE_PASSWORD"] %>
  
